# Generated by Django 4.1.6 on 2023-04-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": ("Новость",), "verbose_name_plural": "Новости"},
        ),
    ]
